// 配方类型名称映射
export const RECIPE_TYPE_NAMES: Record<string, string> = {
  "minecraft:crafting_shaped": "有序合成",
  "crafting_shaped": "有序合成",
  "minecraft:crafting_shapeless": "无序合成",
  "crafting_shapeless": "无序合成",
  "minecraft:smelting": "熔炼",
  "smelting": "熔炼",
  "minecraft:blasting": "高温熔炼",
  "blasting": "高温熔炼",
  "minecraft:smoking": "烟熏",
  "smoking": "烟熏",
  "minecraft:campfire_cooking": "营火烹饪",
  "campfire_cooking": "营火烹饪",
  "stonecutting": "切石",
  "minecraft:stonecutting": "切石",
  "smithing": "锻造",
  "minecraft:smithing": "锻造",
  "smithing_trim": "锻造模具",
  "minecraft:smithing_trim": "锻造模具",
  "enderio:alloy_smelting": "合金熔炼 (EnderIO)",
  "actuallyadditions:empowering": "原子强化 (AA)",
  "immersiveengineering:arc_furnace": "电弧炉 (IE)",
  "immersiveengineering:crusher": "粉碎机 (IE)",
  "immersiveengineering:squeezer": "工业压榨 (IE)",
  "immersiveengineering:fermenter": "发酵池 (IE)",
  "immersiveengineering:metal_press": "金属冲压 (IE)",
  "immersiveengineering:blast_furnace": "粗制焦炉 (IE)",
  "immersiveengineering:coke_oven": "焦炭炉 (IE)",
  "immersiveengineering:alloy": "合金窑 (IE)",
  "thermal:smelter": "感应熔炉 (Thermal)",
  "thermal:pulverizer": "磨粉机 (Thermal)",
  "thermal:sawmill": "锯木厂 (Thermal)",
  "thermal:press": "多功能压机 (Thermal)",
  "thermal:crucible": "熔化炉 (Thermal)",
  "thermal:chiller": "流体转注机 (Thermal)",
  "thermal:refinery": "精炼厂 (Thermal)",
  "thermal:centrifuge": "离心机 (Thermal)",
  "thermal:brewer": "炼药机 (Thermal)",
  "mekanism:crushing": "粉碎 (Mekanism)",
  "mekanism:enriching": "富集 (Mekanism)",
  "mekanism:smelting": "熔炼 (Mekanism)",
  "mekanism:purifying": "净化 (Mekanism)",
  "mekanism:injecting": "注入 (Mekanism)",
  "mekanism:compressing": "压缩 (Mekanism)",
  "mekanism:sawing": "锯木 (Mekanism)",
  "advanced_ae:reaction": "高级反应",
  "mekanism:metallurgic_infusing": "冶金灌注",
  "mekanism:combining": "压缩",
  "mekanism:chemical_infusing": "化学注入",
  "mekanism:dissolution": "溶解",
  "mekanism:washing": "化学清洗",
  "mekanism:crystallizing": "结晶",
  "mekanism:reaction": "加压反应",
  "mekanism:centrifuging": "同位素离心",
  "mekanism:nucleosynthesizing": "反物质核合成",
  "create:mixing": "动力搅拌",
  "create:crushing": "粉碎轮",
  "create:pressing": "压片",
  "create:cutting": "切割",
  "create:milling": "石磨",
  "create:compacting": "压块",
  "create:haunting": "缠魂",
  "create:splashing": "洗涤",
  "create:deploying": "机械手",
  "create:filling": "流体填充",
  "create:emptying": "流体排空",
  "create:sequenced_assembly": "动力装配",
};
